name: tution
description: A tuition class management app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  supabase_flutter: 2.9.0
  intl: ^0.18.1
  uuid: ^3.0.7
  image_picker: ^1.0.0
  fl_chart: ^0.63.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  sign_in_with_apple: 7.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
